version: "3.8"

services:
  base:
    build: ./
    ports:
      - 8000:8000
    container_name: server_service
    links:
      - wordpress
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./wordpress:/public/www

  mysql:
    image: mysql:${MYSQL_VERSION} 
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    container_name: mysql_service

  wordpress:
    image: wordpress:${WORDPRESS_VERSION}
    volumes:
      - ./wordpress:/var/www/html
      - ./wordpress:/public/www
    links:
      - mysql
    ports:
      - 8080:9000
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: ${MYSQL_ROOT_PASSWORD}
      WORDPRESS_DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    container_name: wordpress_service
